version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - DB_HOST=db

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}